service: react-frontend-service

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

resources:
  Resources:
    ReactAppBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-react-app-bucket
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    ReactAppBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ReactAppBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: !Sub "arn:aws:s3:::${ReactAppBucket}/*"

functions:
  deployReactApp:
    handler: handler.deploy
    events:
      - s3:
          bucket: my-react-app-bucket
          event: s3:ObjectCreated:*
          rules:
            - suffix: .html