service: react-frontend-service

provider:
  name: aws
  region: us-east-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: my-react-app-bucket-${self:provider.region}
    distributionFolder: build

resources:
  Resources:
    ReactAppBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.client.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    ReactAppBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ReactAppBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: !Sub "arn:aws:s3:::${self:custom.client.bucketName}/*"